### ISSUE TITLE
the texts are very right side view - ltsp.conf man home pages

### ISSUE THREAD

**Issue by doguibnu** [ltsp/ltsp.github.io#1]
Hello All
At ltsp.conf man home page:
[https://ltsp.github.io/man/ltsp.conf/](https://ltsp.github.io/man/ltsp.conf/)

problem to see the right text alignment after text - PARAMETER. the texts are very right side view until next title: EXAMPLES 

View in Firefox 69 - Linux

Thanks for attention

Douglas

**Comment by alkisg** [comment]
Thank you Douglas, yeah I know, I just prepared the website yesterday and I didn't yet have time to find a way to make them appear good both in .md and in man page format.

Will look into it next.

**Comment by alkisg** [comment]
Fixed with https://github.com/ltsp/ltsp.github.io/blob/master/_sass/overrides.scss.

Thanks again Douglas! :smile:
